// {
//     "id": "25567",
//     "memberNo": "0000003",
//     "memNo": "0000003",
//     "fullName": "MEMBER  TEST",
//     "name": "MEMBER  TEST",
//     "approved": "Yes",
//     "sponsorId": "3453",
//     "classId": "6402",
//     "companyId": "6399",
//     "memberBioId": "25566",
//     "gender": "Male",
//     "membershipStatus": "Died In Service",
//     "partyRefNo": "MEMBERTEST01/01/19971234567893",
//     "policyNo": "3",
//     "partnerNo": "-",
//     "nationalPenNo": "-",
//     "dateJoinedScheme": "May 5, 2020",
//     "dateOfEmployment": "Jan 1, 2020",
//     "dob": "Jan 1, 1997",
//     "email": "wilfredkim5@gmail.com",
//     "idNo": "123456789",
//     "taxPin": "A123456789H",
//     "age": "23",
//     "ageDecimals": "23.59",
//     "primaryPhone": "0723787120",
//     "secondaryPhone": "-",
//     "status": "DEATH_IN_SERVICE",
//     "statusName": "Death_In_Service",
//     "department": "-",
//     "region": "-",
//     "jobGrade": "-",
//     "sponsorName": "SYSTECH LIMITED PENSION SCHEME SPONSOR",
//     "memberClassName": "SYSTECH MEMBER CLASS",
//     "companyName": "SYSTECH LIMITED PENSION SCHEME Sponsor Cost Centre",
//     "countBeneficiaries": "0",
//     "biometricReged": "Not Registered",
//     "biometricRegBy": "-",
//     "biometricDateReged": "-",
//     "lifestyleProfile": "",
//     "schemeId": "3449"
// },
Ext.define('Xe.model.members.Member', {
    extend: 'Xe.model.Base',
    requires: ['Xe.util.Util'],
    fields: [
        { name: 'id', type: 'int' },
        { name: 'memberNo', type: 'int' },
        { name: 'id', type: 'int' },
        { name: 'memberNo', type: 'int' },
        { name: 'memNo', type: 'int' },
        { name: "fullName" },
        { name: "name", type: "string" },
        { name: "approved", type: "string" },
        { name: "sponsorId", type: 'int' },
        { name: "classId", type: 'int' },
        { name: "companyId", type: 'int' },
        { name: "memberBioId", type: 'int' },
        { name: "gender" },
        { name: "membershipStatus" },
        { name: "partyRefNo" },
        { name: "policyNo" },
        { name: "partnerNo" },
        { name: "nationalPenNo" },
        { name: "dateJoinedScheme" },
        { name: "dateOfEmployment" },
        { name: "dob" },
        { name: "email" },
        { name: "idNo", type: 'int' },
        { name: "taxPin" },
        { name: "age" },
        { name: "ageDecimals" },
        { name: "primaryPhone" },
        { name: "secondaryPhone" },
        { name: "status" },
        { name: "statusName" },
        { name: "department" },
        { name: "region" },
        { name: "jobGrade" },
        { name: "sponsorName" },
        { name: "memberClassName" },
        { name: "companyName" },
        { name: "countBeneficiaries" },
        { name: "biometricReged" },
        { name: "biometricRegBy" },
        { name: "biometricDateReged" },
        { name: "lifestyleProfile" },
        { name: "schemeId", type: 'int' },
    ],
    proxy: {
        type: 'ajax',
        url: 'resources/members.json',
        reader: {
            type: 'json',
            rootProperty: 'rows',
            totalProperty: 'totalCount'

        }
    },
    // autoLoad: true,
    listeners: { //#6
        exception: function(proxy, response, operation) {
            Xe.util.Util.showErrorMsg(response.responseText);
        }
    }
});